Add a column to capture Treated for Cervical Cancer and treatment opt…
palladiumkenya/openmrs-module-kenyakeypop pull request #196
Opened 2024-06-18 06:03 UTC by gabriel090

Add a column to capture Treated for Cervical Cancer and treatment options are (Y/ N/ N/A)
Add a column to capture PrEP Status and the status options are (Initiated-I/ Refill-RF/ Restart-RS/ Discontinued-D/ NA)

2024-06-18 18:24 UTC, njorocs requested changes

2024-06-18 18:24 UTC, njorocs commented on api/src/main/java/org/openmrs/module/kenyakeypop/reporting/data/converter/definition/evaluator/kp/TreatmentForCervicalCancerDataEvaluator.java
> +		String qry = "  SELECT patient_id,coalesce(\n" +
what is coalesce for?
The query does not have a time frame. Add start and end date to the query. Ensure the same are injected from the builder.
There are repeated parts in the query.
optimise the case part thus;

CASE
        WHEN cervical_cancer = 'Yes'
            AND hpv_screening_method = 'HPV'
            AND via_vili_screening_method = 'VIA' THEN
            CASE
                WHEN hpv_screening_result = 'Positive'
                    AND via_vili_screening_result = 'Positive'
                    AND colposcopy_treatment_method IS NOT NULL
                    AND colposcopy_treatment_method <> ''
                    THEN 'Y'
                WHEN hpv_screening_result IN ('Positive', 'Negative')
                    AND (colposcopy_treatment_method IS NULL
                        OR colposcopy_treatment_method = '')
                    THEN 'N'
                ELSE 'NA'
                END
        ELSE 'NA'
        END AS result

2024-06-19 17:48 UTC, gabriel090 commented on api/src/main/java/org/openmrs/module/kenyakeypop/reporting/data/converter/definition/evaluator/kp/PrePStatusDataEvaluator.java
> +		        + "from kenyaemr_etl.etl_prep_followup v where date(v.visit_date) between date(:startDate) and date(:endDate)\n"
Ok. Worked on them

2024-06-19 17:48 UTC, gabriel090 commented on api/src/main/java/org/openmrs/module/kenyakeypop/reporting/data/converter/definition/evaluator/kp/TreatmentForCervicalCancerDataEvaluator.java
> +		String qry = "  SELECT patient_id,coalesce(\n" +
Thanks. Worked on the Query

2024-06-28 06:36 UTC, merged