KVP LHIV TRACKER OFFSITE REGISTER
palladiumkenya/openmrs-module-kenyakeypop pull request #199
Opened 2024-06-26 09:54 UTC by gabriel090

Add KVP LHIV tracker offsite register in the EMR to help DICEs track those clients who receive Care and Treatment service from  a different facility other than where they receive KVP services.

The source document for the register is the PLHIV Link Facility form.

2024-08-15 07:17 UTC, njorocs requested changes
Revise the queries to use PLHIV Link Facility Documentation Tracking form as the primary and then treatment verifcation as secondary for accuracy

2024-08-15 13:53 UTC, gabriel090 commented on api/src/main/java/org/openmrs/module/kenyakeypop/reporting/cohort/definition/evaluator/KvpLHIVTrackingRegisterCohortDefinitionEvaluator.java
> +		String qry = "select v.client_id from kenyaemr_etl.etl_clinical_visit v\n"
> KPLHIV means KPs living with HIV. This cohort query does not do that.

Worked on It. Thanks

2024-08-15 13:53 UTC, gabriel090 commented on api/src/main/java/org/openmrs/module/kenyakeypop/reporting/data/converter/definition/evaluator/kp/FinalTransitionOutcomeDataEvaluator.java
> +		        + "       case tr.true_status\n"
fixed.

2024-08-16 09:38 UTC, njorocs requested changes

2024-08-16 09:38 UTC, njorocs commented on api/src/main/java/org/openmrs/module/kenyakeypop/reporting/data/converter/definition/evaluator/kp/IPTStartedDateDataEvaluator.java
> +		String qry = "SELECT  t1.client_id, COALESCE(t1.IPT_start_date, t2.date_initiated_tpt) AS IPT_start_date\n"
select from a parent table and left join with these either or tables.

2024-08-16 09:38 UTC, njorocs commented on api/src/main/java/org/openmrs/module/kenyakeypop/reporting/data/converter/definition/evaluator/kp/OppotunisticInfectiousDiagnosedDateDataEvaluator.java
> +		String qry = "SELECT  t1.client_id, COALESCE(t1.oi_diagnosis_date, t2.date_diagnosed) AS oi_diagnosis_date\n"
select from a parent table and left join with these either or tables.

2024-08-19 11:54 UTC, gabriel090 commented on api/src/main/java/org/openmrs/module/kenyakeypop/reporting/cohort/definition/evaluator/KvpLHIVTrackingRegisterCohortDefinitionEvaluator.java
> +		String qry = "select \n" + "    v.client_id, \n"
I have rectified

2024-10-03 05:41 UTC, njorocs approved these changes
merging for testing.

2024-10-03 05:41 UTC, merged